### PR TITLE
add ${HEALTH_CHECK_URL}

### PR DESCRIPTION
**Pull request by nicholasklem**
Google Kubernetes Engine Load Balancer has a limitation in that the health checks need to return 200 OK. So I added a /${HEALTH_CHECK_URL} endpoint.

### CODE REVIEW

**Comment by schmunk42** [comment]
@nicholasklem Could you also add a line to https://github.com/schmunk42/docker-nginx-redirect#environment-variables

Rest LGTM, waiting for feedback from @handcode

**Comment by nicholasklem** [comment]
I changed the name of the variable from HEALTH_CHECK_URL to HEALTH_CHECK_PATH, since it only is configurable as a location stanza in Nginx.

**Comment by handcode** [comment]
I like the idea, but if HEALTH_CHECK_PATH is not explicitly set, we should not do any special handling for any location.

Because even if it is unlikely that there is a valid URL with the default value for HEALTH_CHECK_PATH, as it is now, we always define a location that is not redirected as expected, even if the user does not want or need it.

IMHO we shouldn't guess which URLs other users don't need ;-)

**Comment by nicholasklem** [comment]
Mm, I agree. I started down this road, but I saw no practical way to express this in the bash templating setup. Feel free to discard the pull request and I'll run my own branch for now.

**Comment by nicholasklem** [comment]
Altered the logic, so setting HEALTH_CHECK_PATH now includes the location stanza.

It detracts from the simplicity of run.sh, and I believe if one has fallen this deep into the rabbit hole you might as well handcraft the config.

Feel free to decline.

**Comment by schmunk42** [comment]
@handcode WDYT?

**Pull request closed without merging**
