### PR TITLE
Add handling for POST requests separately; Support additional response codes

### PR DESCRIPTION
**Pull request by Hossy**
Add support for POST redirects via a 307 per RFC 7231. https://tools.ietf.org/html/rfc7231#section-6.4.7

### CODE REVIEW

**Comment by handcode** [comment]
IMHO it is not a good idea to hardcode status code for all (but only for) POST requests.
- per default this will mix permanent and temporary redirects
- what if anyone don't want 307 for POST?
- what if anyone want redirect permanent also for POST with 301 or 308
- ...

If we want to be able to use a specific status code, it should be configurable and then used for all requests.

I have made a patch which make it possible to define 307 via ENV `SERVER_REDIRECT_CODE`. see #9

**Comment by schmunk42** [comment]
@Hossy Could you take a look at #9 and give feedback if this would solve your problems.

**Comment by Hossy** [comment]
The problem is that 308 is an experimental code (https://tools.ietf.org/html/rfc7238) and is not part of the Internet Standards Track.  So, the only "official" code available to redirect a POST (and keep it a POST) is 307.

However, I agree with @handcode and didn't think about being flexible on the POST redirect code.

@schmunk42 I have updated my pull request to support another ENV variable for POST redirects that defaults to 307 if unspecified.

**Comment by Hossy** [comment]
I should also note that for my use case, the desired effect is a permanent redirect for all HTTP calls, but the official standard does not include 308 and using a 301 in response to a POST will cause the client to potentially change the POST to a GET, which is undesired.  The 307 code, specifically for a POST only, enforces the second call to be a POST when following redirection.  While everything else will get the desired 301 response.

**Comment by Hossy** [comment]
Sorry, @schmunk42, I didn't address your question about #9.  I think your addition is acceptable as well and maybe you could merge both my latest commit https://github.com/schmunk42/docker-nginx-redirect/pull/8/commits/b408c111917e3124ce6f47a6cd855e0c7ff5bdeb with that.  However, could you just leave the code value open for any HTTP code?  Validation could be \d{3}.

Arguably, it is the admin/user who is responsible for setting the correct response code.

**Comment by handcode** [comment]
@Hossy your use case (whatever it is) is the special case.  

If we define 307 as default for POST everyone who update this image must reconfigure his containers or will get a different behaviour.

Therefor the default should be to redirect all requests with the same status code as before.

Anyway, i've cherry picked / merged the introducion of a new ENV VAR which can be used to define a special code for POST. see #9 

Does this match your requirements?

And a hint to validation: the nginx documentation clearly says that nginx only accepts 301, 302, 303, 307, and 308 for redirects, so it makes no sense to allow others. see http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return

If we allow eg. 305 nginx wouldn't send a redirect (no location header):
```
HTTP/1.1 305
Server: nginx/1.13.12
Date: Wed, 11 Apr 2018 18:40:54 GMT
Content-Type: application/octet-stream
Content-Length: 40
Connection: keep-alive
```

**Comment by Hossy** [comment]
> @Hossy your use case (whatever it is) is the special case.

@handcode I'm not sure I agree with my use case as being special.  The default for POST requests to 307 is, as currently documented, the best way to maintain all HTTP verbs/requests with redirection.  It is very clearly documented (https://tools.ietf.org/html/rfc7231#section-6.4.2) that a 301 response to a POST may result in a GET, which is not what the client intended (otherwise they would've sent a GET in the first place).

> If we define 307 as default for POST everyone who update this image must reconfigure his containers or will get a different behaviour.
> 
> Therefor the default should be to redirect all requests with the same status code as before.

I thought about the backwards compatibility in regards to the 307 code as well, but I was weighing these two scenarios:
1. Did an existing user knowingly inspect the resulting nginx config and explicitly want POST requests to receive the same redirect code as all other requests?
2. Would the existing user base benefit from the change as most probably don't read the RFCs or inspect the resulting nginx config or understand that a 301 response to a POST will change it to a GET?

My thoughts were that scenario 1 was far less likely and a user who fits into scenario 1 would probably also pay closer attention to an upgrade of the image than a user in scenario 2.  So, a user in scenario 1 would see the change and be able to edit the environment variables to still meet their use case.  While, users in scenario 2, would now benefit from the work of others like us and now have better working redirection.

> And a hint to validation: the nginx documentation clearly says that nginx only accepts 301, 302, 303, 307, and 308 for redirects, so it makes no sense to allow others. see http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return

I also read http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return before posting my fix, but my thoughts on allowing more codes was so this code would not have to be constantly maintained and updated as newer versions of nginx get released and they expand their support of 3xx codes.  The Dockerfile is configured to use the latest version and not a specific version of nginx, so unless @schmunk42 (or someone else) is going to maintain this for as long as nginx:alpine is being updated, it seemed easier to support all 3xx codes to make this as future proof as currently possible.  On the reverse side, I limited the codes to 3xx because the purpose (as I understand it) of this project is specifically for redirection using nginx.  All HTTP redirection RFCs to date reserve the 3xx codes for redirection, even though 8 (300-307) are only currently used with a 9th one (308) being tested.

**Comment by handcode** [comment]
> The default for POST requests to 307 is, as currently documented, the best way to maintain all HTTP verbs/requests with redirection. 

I agree that 307 for POST is the best way **if** you want to preserve POST for the redirect. But IMHO that is the special case for this container. Especially since 307 is not a permanent redirect. 

This container is a simple, general purpose redirect host. No more and no less.

I'm pretty shure in most cases this container is used as a simple way to permanantly redirect all requests from example.net to example.com or to redirect what-ever-marketing-domain.tld to example.com/landingpage. And in most cases the target URI will not expect or even not allow POST (which web server expects POST on the start page?)

> It is very clearly documented (https://tools.ietf.org/html/rfc7231#section-6.4.2) that a 301 response to a POST may result in a GET, which is not what the client intended (otherwise they would've sent a GET in the first place).

A client that sends a POST request to a URI / domain which is only a simple redirect host and expects its non-idempotent request to be successfully processed on another server should generally reconsider its requests...

If I was the client or had written it, I didn't want my POST requests (e.g. with login data or file uploads) to be redirected as POST to another server in any case. I would expect to get an error!

And to allow more values (codes in this case) than the application (nginx in this case) expects for a desired action is a bad practice.

Anyway: It's up to @schmunk42  to decide where he wants to go with this Container.

PS: I've implemented your requirements in #9 . Have you taken a look at this and/or tested it? Is there anything you're missing?

**Comment by Hossy** [comment]
> I agree that 307 for POST is the best way if you want to preserve POST for the redirect. But IMHO that is the special case for this container. Especially since 307 is not a permanent redirect.
> 
> This container is a simple, general purpose redirect host. No more and no less.
> 
> I'm pretty shure in most cases this container is used as a simple way to permanantly redirect all requests from example.net to example.com or to redirect what-ever-marketing-domain.tld to example.com/landingpage. And in most cases the target URI will not expect or even not allow POST (which web server expects POST on the start page?)
> 

You're kind of making my case for me. :-)  And this is why I figured scenario 2 was more likely and less impact because most people are using this image in a simple manner.  But, "simple" doesn't also have to mean that we don't improve the overall function and intended behavior of the application.  In fact, it should be that all the "heavy lifting" like this is done so that a "plug-and-play" user can spin this up and rely on the advertised and intended behavior to be the best possible in all scenarios.

> A client that sends a POST request to a URI / domain which is only a simple redirect host and expects its non-idempotent request to be successfully processed on another server should generally reconsider its requests...
> 
> If I was the client or had written it, I didn't want my POST requests (e.g. with login data or file uploads) to be redirected as POST to another server in any case. I would expect to get an error!
> 

You are correct and that is what RFC 2616 requires: https://tools.ietf.org/html/rfc2616#section-10.3.8
```
   If the 307 status code is received in response to a request other
   than GET or HEAD, the user agent MUST NOT automatically redirect the
   request unless it can be confirmed by the user, since this might
   change the conditions under which the request was issued.
```
... but that doesn't mean that we still shouldn't default to a 307 (over a 301 or 302) because it is the optimal redirect code for a POST (until 308 is accepted), should the client and user choose to act on the redirect.

> And to allow more values (codes in this case) than the application (nginx in this case) expects for a desired action is a bad practice.

I see and understand your argument here, and normally I would agree all things being equal.  But, I have a feeling that @schmunk42 is one person and NGINX is a company of more than one person.  So, resources being what they are, I wanted to make it easier on @schmunk42 to maintain the code moving forward.  At the same time, the risk of a problem is mitigated by the default values 301 and 307 as users who don't configure the redirect code won't have an issue (301 and 307 have already been chosen for them) and users who want to play with different codes are free to do so and will be forced to learn about what codes they should be using.

However, I will edit the Readme.md and add a link to the NGINX documentation to explain the current supported codes and encourage further reading if the user intends on specifying a non-default code.

> PS: I've implemented your requirements in #9 . Have you taken a look at this and/or tested it? Is there anything you're missing?

I have looked at your pull request and no, I don't see anything missing.  Both #8 and #9 are implementing the same functionality in two different ways and I agree we need a tie breaker (@schmunk42) to determine which direction he wants to go with the code.

These have been really long replies and I really appreciate all the feedback and responsiveness from you, @handcode.  If I may, I would like to summarize the two pull requests for @schmunk42 to hopefully make it easier to understand the differences between #8 and #9.

### Summary

Both pull requests implement a new POST request handler that is separate from other requests while still using the same Location response.  Both requests also increase the number of 3xx response codes accepted by the application/user to make all supported codes available for use.  The documentation is updated to explain the use case and the details that are unique to each pull request.

#### Pull Request #8:
Sets the default response code to 307 for POST requests, which we agreed to be the best option for responding with redirection to a POST request.  Allows configuration of all 3xx codes for both the primary redirect and POST redirect.
##### Pros:
* A 307 is the preferred redirection response code for a POST request and is the default response code.
* If NGINX support changes or new codes are added to the supported list, no code changes will be necessary to make the new codes/changes available for use.
##### Cons:
* The HTTP code sent by default for POST requests will change when an existing user upgrades their docker image.  If a user desires a 301 or 302 response to a POST request, the user will need to set the environment variable appropriately.
* A user could specify an unsupported or invalid http response code and cause NGINX to generate errors potentially resulting in no redirection being performed.

#### Pull Request #9:
Sets the default response code for POST requests to match the response code of the primary redirect, unless overridden by the user.  Accepts only 301, 302, 303, 307, and 308 codes per the current NGINX 1.13.12 documentation (http://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return).
##### Pros:
* The HTTP code sent by default for POST requests will remain unchanged when an existing user upgrades their docker image.  No additional configuration is needed.
* If a user specifies an unsupported or invalid http response code, the user configuration will be ignored and the default value will be used.
##### Cons:
* A 301 or 302 response to a POST request is not a desirable response as, per RFC 2616, a 301 or 302 response to a POST will most likely result in the client transforming (not redirecting) the method to a GET request instead, should the client/user choose to follow the redirect.
* If NGINX support changes or new codes are added to the supported list, the regex will need to be updated and distributed to allow users to take advantage of the new options.

**Comment by handcode** [comment]
> ... but that doesn't mean that we still shouldn't default to a 307 (over a 301 or 302) because it is the optimal redirect code for a POST (until 308 is accepted), should the client and user choose to act on the redirect.

That's your opinion. IMHO it is not the optimal because 307 is not a permanent redirect and i'm pretty shure that permanent redirects are the desired behavior for most users of this image.
But obviously we're never gonna agree on this.

> Both #8 and #9 are implementing the same functionality in two different ways

To be clear: I don't need this "feature". I've started my PR to help you to get your requirements in here since it was clear that your first approach (hardcode 307 for POST) would never be merged. Since than i'm wondering why you reimplement everything in parallel.

**Comment by Hossy** [comment]
> That's your opinion.

It isn't just my opinion; it's very clearly documented in the RFCs, if you want a POST request to remain a POST request, which I thought was obvious; I can provide specific references, if needed.

Even if you ignore the reasoning given in the RFCs, I can't think of another reason why the 307 and 308 codes would have been created.  You can't change the behavior of an existing well-known code (301/302) for backwards compatibility and because it would require modification of all existing applications, so you have to extend.

> IMHO it is not the optimal because 307 is not a permanent redirect and i'm pretty shure that permanent redirects are the desired behavior for most users of this image.

As I said before, I agree that a 307 isn't the absolute best method for permanently redirecting a POST -- 308 is the clear choice.  But, 308 is not part of the Internet Standard Track yet.  301 flat out breaks a POST regardless of the choices given to the user by the client (which is why the IETF created 307 and 308).  So, given the "official" options of 301, 302, and 307, 307 is the closest to preserving the original request while still implementing redirection.

To be clear: no permanent redirection is occurring when a POST request receives a 301 response -- the POST request is discarded and the user should be given the option to perform a GET or do nothing.  So, changing to the 307 response at least enables some level of redirection since the permanent variety (308) is not "official" yet.

> But obviously we're never gonna agree on this.
> 
> To be clear: I don't need this "feature". I've started my PR to help you to get your requirements in here since it was clear that your first approach (hardcode 307 for POST) would never be merged. Since than i'm wondering why you reimplement everything in parallel.
> 

It seems now you're just being argumentative, but I will acknowledge my original commit was hard-coding the 307 (I was following along with the current options of "pick 301 or 302" for normal redirection) and your pull request forced me to look deeper into this problem, so thank you.  Because of your work, I've implemented the expansion of the usable codes and agree the responses should be more than just 301 or 302.

I agree that some users, for their own reasons, might want to maintain responding to POST requests with a 301 or 302 if their application requires or expects that type of response, but that would be a unique or special situation and would not apply to the Internet at large.  I'm simply trying to follow RFC which intends on redirection of POST requests to be handled by 307 (and eventually 308 as a permanent redirect).

**Comment by handcode** [comment]
> 
>     That's your opinion.
> 
> It isn't just my opinion; it's very clearly documented in the RFCs, if you want a POST request to remain a POST request, which I thought was obvious; I can provide specific references, if needed.


Your opinion is that this container should forward all POST requests **per default** with status 307.

I beg to differ.

But just because I don't agree with you on that point doesn't mean I didn't understand the meaning of the 307 or 308 codes, what RFCs for or how HTTP works. I'm not stupid.

But i don't want to discuss in cycles.
Thanks and have a good time.

**Comment by Hossy** [comment]
> Your opinion is that this container should forward all POST requests per default with status 307.

I made the presumption that the container would be redirecting all requests instead of either just GETs or everything except POSTs.

**Comment by schmunk42** [comment]
I will take a look at this ASAP. Thank you both, I learned a lot about status codes ;)

**Comment by schmunk42** [comment]
Went for @handcode 's version - both were almost the same. Thank you for your efforts!

**Pull request closed without merging**
