### PR TITLE
Support alternative http code for PUT, PATCH and DELETE methods

### PR DESCRIPTION
**Pull request by oriy**

### CODE REVIEW

**Comment by schmunk42** [comment]
Is this for `PUT` and `PATCH`, what is your use case?

It would be nice if we could create a backward-compatible implementation.

**Comment by oriy** [comment]
Yes @schmunk42, `PUT`, `PATCH` and `DELETE` redirected as GET

Fixed code to be backward-compatible

**Comment by oriy** [comment]
@handcode can you review?

**Comment by handcode** [comment]
sorry for delay.

this change is not backward-compatible.

In you're bc patch SERVER_REDIRECT_POST_CODE is reused as alias for the new SERVER_REDIRECT_OTHER_METHODS_CODE which means it now has a completely different functionality than before.

Currently the VAR only set return-code for POST. With you're patch it would be used for all Methods other than GET|HEAD. This means, for example, that every OPTIONS request will behave different as before.

**Comment by oriy** [comment]
> sorry for delay.
> 
> this change is not backward-compatible.
> 
> In you're bc patch SERVER_REDIRECT_POST_CODE is reused as alias for the new SERVER_REDIRECT_OTHER_METHODS_CODE which means it now has a completely different functionality than before.
> 
> Currently the VAR only set return-code for POST. With you're patch it would be used for all Methods other than GET|HEAD. This means, for example, that every OPTIONS request will behave different as before.

correct
will revise

**Comment by oriy** [comment]
@schmunk42 @handcode please review
backward compatible version

**Review by handcode — APPROVED** [review]
Looks good to me, thanks

**Comment by schmunk42** [comment]
Thank you!

**Pull request merged**
